#theme = "gruvbox"
theme = "base16_default"

[editor]
color-modes = true
auto-completion = true
auto-format = true

[editor.statusline]
left = ["mode", "file-name"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
enable = true

[editor.auto-save]
after-delay.enable = true
after-delay.timeout = 3000

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.soft-wrap]
enable = true

[keys.normal]
y = [":clipboard-yank","yank"]
C-v = [":clipboard-paste-before"]

[keys.insert]
C-c = "normal_mode"

[keys.select]
"C-c" = ["normal_mode", "keep_primary_selection", "collapse_selection"]
y = [":clipboard-yank","yank"]
X = ["extend_line_up", "extend_to_line_bounds"]
